[package]
name = "okeuvo_lite"
version = "0.1.0"
authors = ["Asame Imoni Obiomah"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled"]
